### PR TITLE
Microverse features

### PR DESCRIPTION
**Pull request by Oluwadamilareolusakin**

### CODE REVIEW

**Comment by Oluwadamilareolusakin** [comment]
@bellom Thanks! Error resolved

**Comment by azdrenymeri** [comment]
Hello @Oluwadamilareolusakin 
The problem`ActionView::SyntaxErrorInTemplate in EventsController#show` still persists
I tried to create an event and it shows the error
[Screenshot](https://i.ibb.co/X3tsdFT/screenshot-localhost-3000-2019-10-09-22-36-04.png)

**Comment by Oluwadamilareolusakin** [comment]
@azdrenymeri this is a bit strange as I tested locally

**Comment by Oluwadamilareolusakin** [comment]
Please give me 2 minutes to check before you request changes

**Comment by Oluwadamilareolusakin** [comment]
@azdrenymeri I forgot to push, apologies

**Comment by Oluwadamilareolusakin** [comment]
@SunnyAsar hey man, thanks so much for your kind words. We can talk on slack and I can share my resources with you as well as my framework 😊

**Pull request closed without merging**
